AWSTemplateFormatVersion: '2010-09-09'

Description: Student Result Management System Infrastructure

Resources:

  StudentAppInstance:
    Type: AWS::EC2::Instance

    Properties:
      ImageId: ami-03f4878755434977f
      InstanceType: t2.micro

      SecurityGroups:
        - !Ref StudentSecurityGroup

      KeyName: my-keypair

      Tags:
        - Key: Name
          Value: StudentResultServer

  StudentSecurityGroup:
    Type: AWS::EC2::SecurityGroup

    Properties:
      GroupDescription: Enable HTTP and SSH

      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0


Outputs:

  InstancePublicIP:
    Description: Public IP Address

    Value: !GetAtt StudentAppInstance.PublicIp
